### ISSUE TITLE
Error  CREATE_FAILED: FargateTasksCluster 

### ISSUE THREAD

**Issue by edgehero** [eddmann/serverless-fargate#16]
Hi im trying out your plugin that looks really nice :) 

But on build i am getting this error. am i doing something wrong? 

CREATE_FAILED: FargateTasksCluster (AWS::ECS::Cluster)
Resource handler returned message: "Invalid request provided: CreateCluster Invalid Request: Unable to assume the service linked role. Please verify that the ECS service linked role exists. (Service: AmazonECS; Status Code: 400; Error Code:

**Comment by eddmann** [comment]
Reading through the docs. it seems as though it could be due to the permissions the role/user has that is attempting to create the cluster? https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using-service-linked-roles.html
