### ISSUE TITLE
Add defineTopLevelProperty to avoid serverless warnings

### ISSUE THREAD

**Issue by mars-lan** [eddmann/serverless-fargate#22]
Currently getting the following warning when running serverless commands:

```
Warning: Invalid configuration encountered at 'fargate': unrecognized property 'containerInsights'
```

See https://www.serverless.com/framework/docs/guides/plugins/custom-configuration#top-level-properties-via-definetoplevelproperty for more details.

**Comment by eddmann** [comment]
This looks to be a missed schema def. Have added in the latest release. Thanks for the report.
