### ISSUE TITLE
Support for logs and invoke parameters in serverless cli

### ISSUE THREAD

**Issue by adrianoesch** [eddmann/serverless-fargate#36]
Hi,

I just started using serverless-fargate for a scheduled long running task (i.e. dbt) and deployment seems a breeze, thank you! I'm somewhat missing the `logs` and `invoke` commands in the serverless client. And while I don't think AWS provides manual invocation of fargate tasks, logs might be able be retrieved via command line client. Not sure where to start, but might be able to contribute. 

Thanks again & cheers!

**Comment by eddmann** [comment]
That is an interesting idea, I'm unsure how we could provide the ability to expose the Fargate logs within the `serverless logs` command, and also if we would be able to hook into the `serverless invoke` command. I would be open for seeing possible means of achieving this perhaps and example use-case of when this would be useful :)

**Comment by eddmann** [comment]
Due to the age of this issue I will close this for the time being, but fee free to submit another issue/reopen to discuss more.
