### ISSUE TITLE
.dockerignore not being honored?

### ISSUE THREAD

**Issue by QAnders** [eddmann/serverless-fargate#40]
Well, there doesn't seem to be much action here, which is unfortunate as the plugin works great and does what it should! :)

I'll still ask, as I have run into an issue with our latest repo. We have started using Localstack for running integration tests in our pipeline and Lockalstack creates a subdirectory called `volume` while running.

`volume` is added in `.dockerignore` and works fine if I build the container using `docker build`.

However, deploying through Serverless it seems that the fargate plugin is not honoring the .dockerignore as it is trying to add `volume`:
```
Cannot read file volume/cache/key.json due to: EACCES: permission denied, open '/home/anders/public-api/volume/cache/key.json'
```

I've added a `sudo rm -r volume/*` in the pipeline so it is sorted for now, but it would nice to understand why the plugin is trying to copy the directory excluded in `.dockerignore`...

**Comment by eddmann** [comment]
Hey, apologies for the delayed reply 🤦🏻‍♂️ , currently the plugin takes advantage of the in-built Serverless Framework image building capabilities, if they are supported there then it should be capable within the plugin.

Upon review of how they build up the `docker` command it doesn't look like they support `.dockerignore` files at this time 😢
