### ISSUE TITLE
How to reference the task arn in serverless yml?

### ISSUE THREAD

**Issue by altonotch** [eddmann/serverless-fargate#42]
I'm trying to use this plugin with step function plugin and I need to reference the arn of the created task definition. 

I can see from the code that it is in the outputs, but how do I reference it in the serverless yml?
Any help would be appreaciated 🙏🏽

**Comment by altonotch** [comment]
I used `'Fn::Sub': <task.name + first letter as capital>TaskArn`

So for example, if the configs if:
```
fargate:
  ...
  tasks:
    myTask:
      name: my-task
```

then to reference the task arn:
```
'Fn::Sub': MytaskTaskArn
```

**Comment by rhamnett** [comment]
This could do with being in the docs
