### ISSUE TITLE
container mount points

### ISSUE THREAD

**Issue by linuxmant** [eddmann/serverless-fargate#43]
Hi, first of all thanks for the plugin, it's very useful.
We have about 5 fargate task definitions that I'm migrating to serverless in a much bigger aws structure.
Does the plugin have support for container mount points and also log driver configs?
A couple of our containers need specific mount points and we are logging all activity to awslogs with custom groups and streams.

**Comment by eddmann** [comment]
I think these should be possible using the `cloudFormationResource` extension property. An example is shown within the [README](https://github.com/eddmann/serverless-fargate?tab=readme-ov-file#example)
