### ISSUE TITLE
Add ability to set name of Cluster

### ISSUE THREAD

**Issue by eddmann** [eddmann/serverless-fargate#9]
Currently it is auto-generated within CloudFormation, but it would be useful to be able to specify this upfront.

**Comment by gordonwade** [comment]
Hi @eddmann, thanks for creating this plugin!

I started using this for a project recently, and I realized I needed the feature described in this issue (the ability to give my cluster a custom name). I've created a fork of this repo where I have made that update.

If you're interested, I would be happy to open a PR back to your original (you can see the diff [here](https://github.com/eddmann/serverless-fargate/compare/main...gordonwade:feature/custom_cluster_name?expand=1)). Let me know what you think!

**Comment by eddmann** [comment]
@gordonwade That would be awesome! 😄
